metro_map = {
    'Camaragibe': [('Cosme e Damião', 4)],
    'Cosme e Damião': [('Camaragibe', 4), ('Rodoviária', 3)],
    'Rodoviária': [('Cosme e Damião', 3), ('Curado', 5)],
    'Curado': [('Rodoviária', 5), ('Alto do Céu', 3)],
    'Alto do Céu': [('Curado', 3), ('Coqueiral', 2)],
    'Coqueiral': [('Alto do Céu', 2), ('Tejipió', 2), ('Cavaleiro', 4)],
    'Tejipió': [('Coqueiral', 2), ('Barro', 3)],
    'Barro': [('Tejipió', 3), ('Werneck', 2), ('Coqueiral', 3), ('Recife', 10)],
    'Werneck': [('Barro', 2), ('Santa Luzia', 3)],
    'Santa Luzia': [('Werneck', 3), ('Mangueira', 4)],
    'Mangueira': [('Santa Luzia', 4), ('Ipiranga', 2)],
    'Ipiranga': [('Mangueira', 2), ('Afogados', 5)],
    'Afogados': [('Ipiranga', 5), ('Joana Bezerra', 4), ('Imbiribeira', 5)],
    'Joana Bezerra': [('Afogados', 4), ('Recife', 2)],
    'Recife': [('Joana Bezerra', 2), ('Barro', 10)],
    'Jaboatão': [('Engenho Velho', 5)],
    'Engenho Velho': [('Jaboatão', 5), ('Floriano', 5)],
    'Floriano': [('Engenho Velho', 5), ('Cavaleiro', 12)],
    'Cavaleiro': [('Floriano', 12), ('Coqueiral', 4)],
    'Imbiribeira': [('Afogados', 5), ('Largo da Paz', 3), ('Antônio Falcão', 10)], 
    'Largo da Paz': [('Imbiribeira', 3), ('Aeroporto', 6)],
    'Aeroporto': [('Largo da Paz', 6), ('Prazeres', 5), ('Porta Larga', 6)],
    'Prazeres': [('Aeroporto', 5), ('Monte dos Guararapes', 4), ('Cajueiro Seco', 7)],
    'Cajueiro Seco': [('Prazeres', 7)],
    'Porta Larga': [('Aeroporto', 6), ('Monte dos Guararapes', 4)],
    'Monte dos Guararapes': [('Porta Larga', 4), ('Prazeres', 4)],
    'Antônio Falcão': [('Imbiribeira', 10), ('Shopping', 3)],
    'Shopping': [('Antônio Falcão', 3), ('Tancredo Neves', 3)],
    'Tancredo Neves': [('Shopping', 3), ('Aeroporto', 6)]
}


metro_map_n_pond =  {
    'Camaragibe': [('Cosme e Damião', 1)],
    'Cosme e Damião': [('Camaragibe', 1), ('Rodoviária', 1)],
    'Rodoviária': [('Cosme e Damião', 1), ('Curado', 1)],
    'Curado': [('Rodoviária', 1), ('Alto do Céu', 1)],
    'Alto do Céu': [('Curado', 1), ('Coqueiral', 1)],
    'Coqueiral': [('Alto do Céu', 1), ('Tejipió', 1), ('Cavaleiro', 1)],
    'Tejipió': [('Coqueiral', 1), ('Barro', 1)],
    'Barro': [('Tejipió', 1), ('Coqueiral', 1), ('Werneck', 1)],
    'Werneck': [('Barro', 1), ('Santa Luzia', 1)],
    'Santa Luzia': [('Werneck', 1), ('Mangueira', 1)],
    'Mangueira': [('Santa Luzia', 1), ('Ipiranga', 1)],
    'Ipiranga': [('Mangueira', 1), ('Afogados', 1)],
    'Afogados': [('Ipiranga', 1), ('Joana Bezerra', 1), ('Imbiribeira', 1)],
    'Joana Bezerra': [('Afogados', 1), ('Recife', 1)],
    'Recife': [('Joana Bezerra', 1)],
    'Jaboatão': [('Engenho Velho', 1)],
    'Engenho Velho': [('Jaboatão', 1), ('Floriano', 1)],
    'Floriano': [('Engenho Velho', 1), ('Cavaleiro', 1)],
    'Cavaleiro': [('Floriano', 1), ('Coqueiral', 1)],
    'Imbiribeira': [('Afogados', 1), ('Largo da Paz', 1), ('Antônio Falcão', 1)],
    'Largo da Paz': [('Imbiribeira', 1), ('Aeroporto', 1)],
    'Aeroporto': [('Largo da Paz', 1), ('Prazeres', 1), ('Porta Larga', 1)],
    'Prazeres': [('Aeroporto', 1), ('Monte dos Guararapes', 1), ('Cajueiro Seco', 1)],
    'Cajueiro Seco': [('Prazeres', 1)],
    'Porta Larga': [('Aeroporto', 1), ('Monte dos Guararapes', 1)],
    'Monte dos Guararapes': [('Porta Larga', 1), ('Prazeres', 1)],
    'Antônio Falcão': [('Imbiribeira', 1), ('Shopping', 1)],
    'Shopping': [('Antônio Falcão', 1), ('Tancredo Neves', 1)],
    'Tancredo Neves': [('Shopping', 1), ('Aeroporto', 1)]
}